import { Inter } from "next/font/google";
import "./globals.css";
import LayoutProvider from "@/Components/layoutProvider/LayoutProvider";
import Toast from "@/utils/toast";
import Provider from "@/utils/sessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Provider>
        <Toast />
        <LayoutProvider>
        {children}
        </LayoutProvider>
        </Provider>
        </body>
    </html>
  );
}
